- name: Ensure homebrew is installed
  stat:
    path: '/usr/local/bin/brew'
  register: homebrew_check

- name: Install homebrew
  command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: not homebrew_check.stat.exists

- name: Update homebrew
  homebrew:
    update_homebrew: true

- name: Install packages with homebrew
  homebrew:
    name: '{{ item }}'
    state: present
    upgrade_all: '{{ upgrade_homebrew_packages }}'
  loop: '{{ brew_packages }}'
