- name: Install apps with homebrew
  homebrew:
    name: '{{ brew_packages }}'
    state: latest
    update_homebrew: yes
  with_items: '{{ brew_packages }}'

- name: Install apps with homebrew cask
  homebrew_cask:
    name: '{{ cask_packages }}'
    state: present
  with_items: '{{ cask_packages }}'

- name: Create symlinks for dotfiles
  file:
    src: '{{ item.src }}'
    dest: '~/.{{ item.path }}'
    state: link
    force: yes
  with_filetree: '{{ role_path }}/files'
  when: item.state == 'file'
