- name: Create symlinks for dotfiles
  file:
    src: '{{ item.src }}'
    dest: '~/.{{ item.path }}'
    state: link
    force: yes
  with_filetree: '{{ role_path }}/files'
  when: item.state == 'file'
