- name: MacOS set up
  include:
    install_brew_packages.yml
    install_cask_packages.yml
    install_python_packages.yml
    install_font.yml
    setup_iterm2_perferences.yml
    setup_dotfiles.yml
