- name: Ensure homebrew is installed
  stat:
    path: '/usr/local/bin/brew'
  register: homebrew_check

- name: Install homebrew
  command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: not homebrew_check.stat.exists

- name: Update homebrew
  homebrew:
    update_homebrew: true

- name: Install packages with homebrew
  homebrew:
    name: '{{ brew_packages }}'
    state: present
    upgrade_all: '{{ upgrade_homebrew_packages }}'
  with_items: '{{ brew_packages }}'

- name: Install packages with homebrew cask
  homebrew_cask:
    name: '{{ cask_packages }}'
    state: present
  with_items: '{{ cask_packages }}'

- name: Check for existing dotfiles
  stat:
    path: '{{ item.dest }}'
  register: dotfile_exists
  with_items: '{{ dotfiles }}'

- name: Backup existing dotfiles
  copy:
    src: '{{ item.item.dest }}'
    dest: '{{ item.item.dest }}.backup'
  with_items: '{{ dotfile_exists.results }}'
  when: item.stat.exists

- name: Create symlinks for dotfiles
  file:
    src: "{{ lookup('env','PWD') }}/{{ item.src }}"
    dest: '{{ item.dest }}'
    state: link
    force: yes
    follow: false
  with_items: '{{ dotfiles }}'

- name: Install Inconsolata for Powerline Nerd Font Complete
  copy:
    src: "{{ lookup('env','PWD') }}/fonts/Inconsolata for Powerline Nerd Font Complete.otf"
    dest: '$HOME/Library/Fonts'
    mode: 0644

- name: Make iTerm2 load from dotfiles config
  shell: |
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/dotfiles/iterm2"
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

- name: Install python2 packages
  pip:
    name: neovim
    state: latest
    executable: pip2

- name: Install python3 packages
  pip:
    name: neovim
    state: latest
    executable: pip3
