- name: Check for existing dotfiles
  stat:
    path: '{{ item.dest }}'
  register: dotfile_exists
  loop: '{{ dotfiles }}'

- name: Backup existing dotfiles
  copy:
    src: '{{ item.item.dest }}'
    dest: '{{ item.item.dest }}.backup'
  loop: '{{ dotfile_exists.results }}'
  when: item.stat.exists

- name: Create symlinks for dotfiles
  file:
    src: "{{ lookup('env','PWD') }}/{{ item.src }}"
    dest: '{{ item.dest }}'
    state: link
    force: yes
    follow: false
  loop: '{{ dotfiles }}'
