POWERLEVEL9K_MODE='awesome-fontconfig'

POWERLEVEL9K_APPLE_ICON=$' '
POWERLEVEL9K_HOME_ICON=$' '
POWERLEVEL9K_HOME_SUB_ICON=$' '
POWERLEVEL9K_FOLDER_ICON=$' '
POWERLEVEL9K_VCS_BRANCH_ICON=$' '
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$' '
POWERLEVEL9K_VCS_COMMIT_ICON=$' '
POWERLEVEL9K_VCS_TAG_ICON=$' '
POWERLEVEL9K_OK_ICON=$''
POWERLEVEL9K_FAIL_ICON=$''

POWERLEVEL9K_SHORTEN_DIR_LENGTH=5

POWERLEVEL9K_OS_ICON_FOREGROUND="254"
POWERLEVEL9K_OS_ICON_BACKGROUND="black"

POWERLEVEL9K_DIR_HOME_FOREGROUND="254"
POWERLEVEL9K_DIR_HOME_BACKGROUND="blue"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="254"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="blue"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="254"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="blue"

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='red'

POWERLEVEL9K_TIME_FOREGROUND='black'
POWERLEVEL9K_TIME_BACKGROUND='242'
POWERLEVEL9K_TIME_FORMAT="%D{ %H:%M}"

POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='214'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='black'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='142'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='black'

POWERLEVEL9K_NODE_VERSION_BACKGROUND='142'
POWERLEVEL9K_NODE_VERSION_FOREGROUND='254'

POWERLEVEL9K_STATUS_VERBOSE=false

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs vi_mode rbenv time)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs vi_mode node_version rbenv time)

DEFAULT_USER=$USER
