# Path to zsh folder
export ZSH=$HOME/.zsh

# Using zplug as plugin manager
source ~/.zplug/init.zsh

# Plugins
zplug "djui/alias-tips"
zplug "lib/*", from:oh-my-zsh
zplug "plugins/npm", from:oh-my-zsh
zplug "zplug/zplug"
zplug "zsh-users/zsh-autosuggestions"
zplug "$ZSH/custom/*.zsh", from:local

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

# source $ZSH/oh-my-zsh.sh
source $ZSH/theme/custom.zsh-theme

eval "$(fasd --init auto)"``

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:$HOME/.rvm/bin:$HOME/bin

#THIS MUST BE AT THE END OF THE FILE FOR JENV TO WORK!!!
[[ -s "/Users/awong/.jenv/bin/jenv-init.sh" ]] && source "/Users/awong/.jenv/bin/jenv-init.sh" && source "/Users/awong/.jenv/commands/completion.sh"
