#!/usr/bin/python
# coding=UTF-8
import re;
import os;

# all those glyphs will show as weird squares if you don't have the correct patched font
file_node_extensions = {
    '.ai'        : '',
    '.bash'      : '',
    '.bat'       : '',
    '.bmp'       : '',
    '.c'         : '',
    '.c++'       : '',
    '.cc'        : '',
    '.clj'       : '',
    '.cljc'      : '',
    '.cljs'      : '',
    '.coffee'    : '',
    '.conf'      : '',
    '.cp'        : '',
    '.cpp'       : '',
    '.css'       : '',
    '.cxx'       : '',
    '.d'         : '',
    '.dart'      : '',
    '.db'        : '',
    '.diff'      : '',
    '.dump'      : '',
    '.edn'       : '',
    '.ejs'       : '',
    '.erl'       : '',
    '.f#'        : '',
    '.fish'      : '',
    '.fs'        : '',
    '.fsi'       : '',
    '.fsscript'  : '',
    '.fsx'       : '',
    '.gif'       : '',
    '.go'        : '',
    '.hbs'       : '',
    '.hrl'       : '',
    '.hs'        : '',
    '.htm'       : '',
    '.html'      : '',
    '.ico'       : '',
    '.ini'       : '',
    '.java'      : '',
    '.jl'        : '',
    '.jpeg'      : '',
    '.jpg'       : '',
    '.js'        : '',
    '.json'      : '',
    '.jsx'       : '',
    '.less'      : '',
    '.lhs'       : '',
    '.lua'       : '',
    '.markdown'  : '',
    '.md'        : '',
    '.ml'        : 'λ',
    '.mli'       : 'λ',
    '.mustache'  : '',
    '.php'       : '',
    '.pl'        : '',
    '.pm'        : '',
    '.png'       : '',
    '.psb'       : '',
    '.psd'       : '',
    '.py'        : '',
    '.pyc'       : '',
    '.pyd'       : '',
    '.pyo'       : '',
    '.rb'        : '',
    '.rlib'      : '',
    '.rs'        : '',
    '.rss'       : '',
    '.scala'     : '',
    '.scss'      : '',
    '.sh'        : '',
    '.slim'      : '',
    '.sln'       : '',
    '.sql'       : '',
    '.styl'      : '',
    '.suo'       : '',
    '.t'         : '',
    '.ts'        : '',
    '.twig'      : '',
    '.vim'       : '',
    '.xul'       : '',
    '.yml'       : '',
    '.zsh'       : '',
    '.zsh-theme' : '',
}

file_node_exact_matches = {
    '.bashprofile'                     : '',
    '.bashrc'                          : '',
    '.ds_store'                        : '',
    '.gitconfig'                       : '',
    '.gitignore'                       : '',
    '.vimrc'                           : '',
    '.zshenv'                          : '',
    '.zshrc'                           : '',
    'dropbox'                          : '',
    'exact-match-case-sensitive-1.txt' : 'X1',
    'exact-match-case-sensitive-2'     : 'X2',
    'favicon.ico'                      : '',
    'gitconfig'                        : '',
    'gitignore'                        : '',
    'gruntfile.coffee'                 : '',
    'gruntfile.js'                     : '',
    'gruntfile.ls'                     : '',
    'gulpfile.coffee'                  : '',
    'gulpfile.js'                      : '',
    'gulpfile.ls'                      : '',
    'license'                          : '',
    'node_modules'                     : '',
    'procfile'                         : '',
    'react.jsx'                        : '',
    'vimrc'                            : '',
    'zshenv'                           : '',
    'zshrc'                            : '',
}

def devicon(file):
    filename, file_extension = os.path.splitext(file)
    if os.path.isdir(file): return ''
    return file_node_exact_matches.get(file, file_node_extensions.get(file_extension, ''))
